import LetterMode from "../LetterMode.js";

export default class TibiaMode extends LetterMode {
  static Name = "Tibia";
  static Id = 6;
  constructor() {
    super(TibiaMode.Id, TibiaMode.Name);
  }
  static Data = [
    "checka din viplist ambellyn loggar in",
    "jammed sneaky stabber of eliteness",
    "jammed squeezing gear of girlpower",
    "simon the beggar's favorite staff",
    "jammed whacking driller of fate",
    "witches cauldron plant (rotten)",
    "Raymond Striker's lucky pillow",
    "Countess Sorrow's frozen tear",
    "remains of an earth elemental",
    "sacred bowl with sacred water",
    "remains of a water elemental",
    "part of a giant stone dragon",
    "Overcharged Energy Elemental",
    "the remains of a spider egg",
    "spellbook of dark mysteries",
    "the remains of an elemental",
    "golden trophy of excellence",
    "silver trophy of excellence",
    "bronze trophy of excellence",
    "claw of 'The Noxious Spawn'",
    "mighty helm of green sparks",
    "sneaky stabber of eliteness",
    "squeezing gear of girlpower",
    "golden lightbearer's trophy",
    "silver lightbearer's trophy",
    "half-digested piece of meat",
    "book of necromantic rituals",
    "sacred bowl of purification",
    "Fallen Mooh'tah Master Ghar",
    "giant glimmer cap mushroom",
    "butterfly conservation kit",
    "wrecked ship cabin railing",
    "Deadeye Devious' eye patch",
    "concentrated demonic blood",
    "scale from a frozen dragon",
    "spellbook of enlightenment",
    "stale bread of ancientness",
    "shield of the white knight",
    "plans for a strange device",
    "piece of crocodile leather",
    "green cushioned chair kit",
    "monkey statue 'speak' kit",
    "wrecked ventilation grill",
    "Ceiron's wolf tooth chain",
    "slain hand of cursed fate",
    "piece of Massacre's shell",
    "building plans for a ship",
    "Elethriel's elemental bow",
    "oceanborn leviathan armor",
    "spellbook of mind control",
    "spellscroll of prophecies",
    "remains of a vampire lord",
    "trophy of a strange being",
    "sample of sand wasp honey",
    "bowl of evergreen flowers",
    "remains of a mercury glob",
    "fried tropical terrorbird",
    "helmet of ultimate terror",
    "fan doll of King Tibianus",
    "dead lizard dragon priest",
    "high guard shoulderplates",
    "Jean Pierre's Cookbook II",
    "Blistering Fire Elemental",
    "light magic missile rune",
    "heavy magic missile rune",
    "dead lizard snakecharmer",
    "monkey statue 'hear' kit",
    "piece of draconian steel",
    "huge chunk of crude iron",
    "very noble-looking watch",
    "easy inflammable sulphur",
    "small enchanted sapphire",
    "small enchanted amethyst",
    "document of the follower",
    "piece of a broken amulet",
    "trophy of a strange fish",
    "sample of venorean spice",
    "trousers of the ancients",
    "fan club membership card",
    "Incredible Mumpiz Slayer",
    "whacking driller of fate",
    "scribbled sheet of paper",
    "flask of embalming fluid",
    "Charged Energy Elemental",
    "Massive Energy Elemental",
    "white stone wall window",
    "red cushioned chair kit",
    "monkey statue 'see' kit",
    "wrecked ship cabin wall",
    "dead thornback tortoise",
    "Brutus Bloodbeard's hat",
    "note pinned on the wall",
    "dwarven emperor's beard",
    "remains of a spider web",
    "small enchanted emerald",
    "document of the officer",
    "energy blacksteel sword",
    "ornamented stone pillar",
    "Koshei's ancient amulet",
    "Jerom's family necklace",
    "lump of chocolate dough",
    "windborn colossus armor",
    "spellbook of lost souls",
    "sparking rainbow shield",
    "remains of an elemental",
    "remains of a death glob",
    "remains of an acid glob",
    "filled jalapeño peppers",
    "crumpled piece of paper",
    "broken gladiator shield",
    "piece of hellfire armor",
    "elder beholder tentacle",
    "dead lizard legionnaire",
    "dead draken spellweaver",
    "warmaster's wristguards",
    "interdimensional potion",
    "girlish hair decoration",
    "small flask of eyedrops",
    "sweet mangonaise elixir",
    "dead draken abomination",
    "Darakan the Executioner",
    "Enlightened of the Cult",
    "Massive Earth Elemental",
    "Massive Water Elemental",
    "Roaring Water Elemental",
    "Quara Constrictor Scout",
    "Quara Hydromancer Scout",
    "Quara Constrictor Scout",
    "convince creature rune",
    "helmet of the ancients",
    "ornamented stone table",
    "christmas tree package",
    "witches cauldron plant",
    "sheet of tracing paper",
    "dead quara constrictor",
    "dead quara hydromancer",
    "enigmatic voodoo skull",
    "enchanted chicken wing",
    "Ron the Ripper's sabre",
    "blue christmas garland",
    "green christmas bundle",
    "Mr. Punish's handcuffs",
    "Handmaiden's protector",
    "small crack in the ice",
    "bale of yellowed cloth",
    "blank poetry parchment",
    "giant shimmering pearl",
    "rotten heart of a tree",
    "fiery blacksteel sword",
    "document of the leader",
    "earth blacksteel sword",
    "nature magic spellbook",
    "ultimate health potion",
    "robe of the underworld",
    "Tibiacity encyclopedia",
    "suspicious present bag",
    "jug of embalming fluid",
    "torso of a jester doll",
    "slain undead gladiator",
    "dead young sea serpent",
    "banana chocolate shake",
    "mechanical fishing rod",
    "tattered piece of robe",
    "bundle of cursed straw",
    "filled carrying device",
    "flash with beaver bait",
    "essence of a bad dream",
    "dead lizard high guard",
    "cursed shoulder spikes",
    "wailing widow necklace",
    "replica of the sceptre",
    "the tail of the keeper",
    "scroll of heroic deeds",
    "snake god's wristguard",
    "Colerian The Barbarian",
    "Barbarian Headsplitter",
    "Frost Dragon Hatchling",
    "Jagged Earth Elemental",
    "Blazing Fire Elemental",
    "Massive Fire Elemental",
    "green cushioned chair",
    "small turqoise pillow",
    "round turqoise pillow",
    "wand of cosmic energy",
    "ultimate healing rune",
    "boots of waterwalking",
    "lady in the fog plant",
    "tanned brown bear fur",
    "tanned polar bear fur",
    "old and used backpack",
    "jungle umbrella plant",
    "slime table mushrooms",
    "glimmer cap mushrooms",
    "the remains of a mast",
    "slain pirate skeleton",
    "perfect behemoth fang",
    "yellow piece of cloth",
    "slain betrayed wraith",
    "remains of a phantasm",
    "red christmas garland",
    "blue christmas bundle",
    "frozen pendulum clock",
    "dead dragon hatchling",
    "energy cranial basher",
    "earthborn titan armor",
    "master archer's armor",
    "terran rainbow shield",
    "slain mutated pumpkin",
    "key of numerous locks",
    "head of a jester doll",
    "part of a jester doll",
    "worn firewalker boots",
    "golden warrior trophy",
    "silver warrior trophy",
    "bronze warrior trophy",
    "broken limestone wall",
    "the shield nevermourn",
    "engraved wedding Ring",
    "the famous golden bug",
    "piece of scarab shell",
    "demonic skeletal hand",
    "frosty ear of a troll",
    "dead draken warmaster",
    "rotten piece of cloth",
    "strand of medusa hair",
    "fluffy santa backpack",
    "zaogun shoulderplates",
    "dragon priest wandtip",
    "flask of plant poison",
    "part of snake sceptre",
    "broken shamanic staff",
    "elven astral observer",
    "piece of archer armor",
    "flexible dragon scale",
    "Barbarian Bloodwalker",
    "Barbarian Skullhunter",
    "Dragon Lord Hatchling",
    "Muddy Earth Elemental",
    "Slick Water Elemental",
    "Quara Mantassin Scout",
    "wand of dragonbreath",
    "intense healing rune",
    "slain crypt shambler",
    "broken lizard statue",
    "pile of chopped wood",
    "devil's tongue plant",
    "slime table mushroom",
    "cat's food mushrooms",
    "glimmer cap mushroom",
    "dead lizard sentinel",
    "flask of cough syrup",
    "botanist's container",
    "dead quara mantassin",
    "blooming griffinclaw",
    "green dragon leather",
    "piece of royal steel",
    "white piece of cloth",
    "green piece of cloth",
    "brown piece of cloth",
    "pirate knee breeches",
    "damaged steel helmet",
    "remains of ferumbras",
    "blessed wooden stake",
    "remains of Ferumbras",
    "Lethal Lissy's shirt",
    "remains of a spectre",
    "red christmas bundle",
    "Plasmother's remains",
    "glowing skull pillar",
    "slain crystal spider",
    "scrying crystal ball",
    "strong health potion",
    "intelligence reports",
    "suspicious documents",
    "fiery cranial basher",
    "small enchanted ruby",
    "icy blacksteel sword",
    "earth cranial basher",
    "energy barbarian axe",
    "energy clerical mace",
    "flawless ice crystal",
    "fireborn giant armor",
    "spellbook of warding",
    "fiery rainbow shield",
    "piece of royal satin",
    "alchemists' formulas",
    "alchemical apparatus",
    "dead nightmare scion",
    "roasted dragon wings",
    "heated worm punisher",
    "silver cup of honour",
    "bronze cup of Honour",
    "pointed rabbitslayer",
    "scythe of the reaper",
    "poet's fencing quill",
    "piece of marble rock",
    "slain ghastly dragon",
    "unworked sacred wood",
    "elven scouting glass",
    "kongra's shoulderpad",
    "shield of corruption",
    "trashed draken boots",
    "Barbarian Brutetamer",
    "Lord of the Elements",
    "Damaged Worker Golem",
    "Quara Predator Scout",
    "white stone railing",
    "red cushioned chair",
    "small purple pillow",
    "small orange pillow",
    "round purple pillow",
    "burnt down firewood",
    "great fireball rune",
    "backpack of holding",
    "dragon scale helmet",
    "dead ancient scarab",
    "dead elder beholder",
    "large stone carving",
    "broken stone pillar",
    "some pieces of wood",
    "minotaur statue kit",
    "camouflage backpack",
    "trashed wooden bars",
    "templar scytheblade",
    "jungle dweller bush",
    "lizards tongue bush",
    "green fountain bush",
    "cat's food mushroom",
    "dead lizard templar",
    "ectoplasm container",
    "bunch of sugar cane",
    "dead quara predator",
    "message in a bottle",
    "piece of hell steel",
    "blue piece of cloth",
    "spellbook of Dragha",
    "slain undead dragon",
    "ornamented fountain",
    "skeleton decoration",
    "purple kiss blossom",
    "bale of white cloth",
    "great health potion",
    "fiery barbarian axe",
    "fiery clerical mace",
    "earth barbarian axe",
    "earth clerical mace",
    "energy mystic blade",
    "energy dragonslayer",
    "energy crystal mace",
    "something sparkling",
    "some special leaves",
    "great spirit potion",
    "small health potion",
    "witchhunter's cloak",
    "slain rotworm queen",
    "TibiaHispano emblem",
    "vampire lord statue",
    "charged ghost charm",
    "suspicious cauldron",
    "northern fishburger",
    "cherry blossom tree",
    "heavy metal t-shirt",
    "broken wedding ring",
    "piece of dead brain",
    "bunch of troll hair",
    "apocalypse mushroom",
    "expedition backpack",
    "ghastly dragon head",
    "lancer beetle shell",
    "lucky clover amulet",
    "lump of sacred clay",
    "pile of grave earth",
    "poison spider shell",
    "coconut shrimp bake",
    "scale of corruption",
    "elite draken helmet",
    "blade of corruption",
    "Norgle Glacierbeard",
    "The Masked Marauder",
    "Chakoya Tribewarden",
    "Acolyte of the Cult",
    "Hand of Cursed Fate",
    "Lizard Snakecharmer",
    "Quara Pincher Scout",
    "adevo mas grav flam",
    "lizard snakecharmer",
    "great fireball rune",
    "white marble floor",
    "black marble floor",
    "rudder of the boat",
    "small green pillow",
    "small white pillow",
    "broken brown glass",
    "broken green glass",
    "worn leather boots",
    "destroy field rune",
    "pair of soft boots",
    "remains of a ghost",
    "remains of a mummy",
    "bamboo wall window",
    "stone snake pagoda",
    "carved stone table",
    "small bamboo shelf",
    "feather decoration",
    "pendulum clock kit",
    "jungle crown plant",
    "small pearl flower",
    "large pearl flower",
    "dead man's saddles",
    "dead serpent spawn",
    "wrinkled parchment",
    "ventilation grille",
    "white stone pillar",
    "old steering wheel",
    "wrecked figurehead",
    "helmet of the deep",
    "burning sugar cane",
    "distilling machine",
    "dead quara pincher",
    "pile of sugar cane",
    "slain pirate ghost",
    "pirate voodoo doll",
    "red piece of cloth",
    "green dragon scale",
    "red dragon leather",
    "lump of cake dough",
    "slain blightwalker",
    "necromancer shield",
    "gingerbread recipe",
    "nordic wall window",
    "Nilsor's waterskin",
    "Nilson's waterskin",
    "frozen plaguesmith",
    "dead silver rabbit",
    "brutetamer's staff",
    "dragon lord trophy",
    "mammoth fur shorts",
    "package of potions",
    "fake dwarven beard",
    "something crawling",
    "strong mana potion",
    "empty potion flask",
    "fiery mystic blade",
    "fiery dragonslayer",
    "fiery crystal mace",
    "icy cranial basher",
    "earth mystic blade",
    "earth dragonslayer",
    "earth crystal mace",
    "energy spike sword",
    "energy relic sword",
    "energy headchopper",
    "energy orcish maul",
    "lightning headband",
    "mysterious machine",
    "mysterious package",
    "inactive lava hole",
    "skullcracker armor",
    "icy rainbow shield",
    "obsidian truncheon",
    "dead rotworm queen",
    "heavily bound book",
    "vampire lord token",
    "dead mutated human",
    "heavy wooden chair",
    "dead vampire bride",
    "old piece of paper",
    "bottle of bug milk",
    "yalahari leg piece",
    "slain nightstalker",
    "crystal of balance",
    "glob of acid slime",
    "hydra tongue salad",
    "golem disassembler",
    "mago mechanic core",
    "limestone pedestal",
    "sacred tree amulet",
    "Leviathan's amulet",
    "slain diabolic imp",
    "wedding outfit box",
    "sea serpent trophy",
    "mystical hourglass",
    "pepper roots grass",
    "dragon scale boots",
    "dead killer caiman",
    "bunch of ripe rice",
    "dead lizard zaogun",
    "dead lizard chosen",
    "dead wailing widow",
    "bone shoulderplate",
    "spellweaver's robe",
    "dead lancer beetle",
    "blood preservation",
    "dead brimstone bug",
    "demonic candy ball",
    "silver rune emblem",
    "golden rune emblem",
    "broken draken mail",
    "tail of corruption",
    "Axeitus Headbanger",
    "Kreebosh the Exile",
    "Big Boss Trolliver",
    "Chakoya Toolshaper",
    "Chakoya Windcaller",
    "Novice of the Cult",
    "Dworc voodoomaster",
    "Grynch Clan Goblin",
    "Thornback Tortoise",
    "adevo mas grav vis",
    "exevo gran vis lux",
    "exura gran mas res",
    "exevo gran mas pox",
    "adevo mas grav pox",
    "exevo gran mas vis",
    "maze of lost souls",
    "dworc voodoomaster",
    " magic plate armor",
    "Thornback Tortoise",
    "The Justice Seeker",
    "Necromancer Shield",
    "white marble tile",
    "black marble tile",
    "gate of expertise",
    "stone wall window",
    "blue shrine stone",
    "closed fence gate",
    "sandstone railing",
    "small round table",
    "small blue pillow",
    "round blue pillow",
    "broken piggy bank",
    "mysterious fetish",
    "stone skin amulet",
    "protection amulet",
    "sudden death rune",
    "energy field rune",
    "poison field rune",
    "stone shower rune",
    "holy missile rune",
    "desintegrate rune",
    "thunderstorm rune",
    "animate dead rune",
    "giant smithhammer",
    "annihilation bear",
    "letter to Markwin",
    "horn of sundering",
    "daramanian waraxe",
    "dragon scale legs",
    "magic plate armor",
    "dragon scale mail",
    "mastermind shield",
    "ornamented shield",
    "sacrificial stone",
    "tic-tac-toe token",
    "post officers hat",
    "sun adorer cactus",
    "bog fingers plant",
    "dead giant spider",
    "split stone golem",
    "carved stone tile",
    "broken stone tile",
    "broken stone wall",
    "grass wall window",
    "giant lizard head",
    "giant lizard claw",
    "rocking chair kit",
    "knight statue kit",
    "large amphora kit",
    "goblin statue kit",
    "rocking horse kit",
    "bamboo drawer kit",
    "feather headdress",
    "salamander shield",
    "dragons nest tree",
    "giant jungle rose",
    "dew kisser flower",
    "dead man's saddle",
    "moss cap mushroom",
    "witches' cap spot",
    "elven poetry book",
    "wrecked ship hull",
    "dead carrion worm",
    "jewelled backpack",
    "Orshabaal's brain",
    "small lava cracks",
    "giant spider silk",
    "Morgaroth's heart",
    "dead orc and wolf",
    "broken brick wall",
    "dead diabolic imp",
    "christmas garland",
    "christmas present",
    "Imperor's trident",
    "wooden decoration",
    "dead frost dragon",
    "resonance crystal",
    "mastermind potion",
    "empty beer bottle",
    "great mana potion",
    "case of rust bugs",
    "techomancer beard",
    "fiery spike sword",
    "fiery relic sword",
    "fiery headchopper",
    "fiery orcish maul",
    "icy barbarian axe",
    "icy clerical mace",
    "earth spike sword",
    "earth relic sword",
    "earth headchopper",
    "earth orcish maul",
    "energy knight axe",
    "energy heroic axe",
    "energy war hammer",
    "lightning pendant",
    "cask of brown ale",
    "remains of Koshei",
    "orcish totem pole",
    "steaming hot lava",
    "deed of ownership",
    "witches' grimoire",
    "your student book",
    "ring of the count",
    "modified crossbow",
    "composite hornbow",
    "crystalline armor",
    "wand of starstorm",
    "dark trinity mace",
    "remains of a wisp",
    "iron construction",
    "large candelabrum",
    "dead worker golem",
    "strange apparatus",
    "crystal table kit",
    "elemental crystal",
    "limestone railing",
    "hellhound slobber",
    "sea serpent scale",
    "mourning mushroom",
    "dry solstice tree",
    "tome of knowledge",
    "carrion worm fang",
    "minotaur backpack",
    "dead orc marauder",
    "legionnaire flags",
    "disgusting trophy",
    "sandcrawler shell",
    "hair of a banshee",
    "geomancer's staff",
    "colourful feather",
    "elite draken mail",
    "dead draken elite",
    "draken wristbands",
    "eye of corruption",
    "ectoplasmic sushi",
    "royal draken mail",
    "Brutus Bloodbeard",
    "Foreman Kneebiter",
    "Tiquandas Revenge",
    "Adept of the Cult",
    "Dworc fleshhunter",
    "Dworc venomsniper",
    "Quara Constrictor",
    "Quara Hydromancer",
    "dworc venomsniper",
    "Quara Constrictor",
    "Quara Hydromancer",
    "Fiery Spike Sword",
    "Dragon Scale Mail",
    "Terracotta Helmet",
    "white stone tile",
    "loose stone pile",
    "cobbled pavement",
    "white stone wall",
    "framework window",
    "sandstone window",
    "red shrine stone",
    "magic forcefield",
    "sandstone statue",
    "empty coal basin",
    "stone coal basin",
    "sandstone pillar",
    "small red pillow",
    "round red pillow",
    "used candelabrum",
    "used candlestick",
    "burnt down torch",
    "lit torch bearer",
    "crystal necklace",
    "wolf tooth chain",
    "demonbone amulet",
    "strange talisman",
    "energy bomb rune",
    "wild growth rune",
    "energy wall rune",
    "poison bomb rune",
    "poison wall rune",
    "Waldo's posthorn",
    "helmet adornment",
    "cobrafang dagger",
    "frozen starlight",
    "two handed sword",
    "guardian halberd",
    "shield of honour",
    "ship's telescope",
    "dead dragon lord",
    "ornamented floor",
    "dried grass roof",
    "small lit pagoda",
    "stone snake wall",
    "small totem pole",
    "large totem pole",
    "tanned tiger fur",
    "wooden chair kit",
    "square table kit",
    "bamboo table kit",
    "indoor plant kit",
    "purple kiss bush",
    "giggle mushrooms",
    "dead terror bird",
    "giant ape's hair",
    "orichalcum pearl",
    "small snake head",
    "piece of a shell",
    "minotaur leather",
    "red dragon scale",
    "Elane's crossbow",
    "nightmare shield",
    "valentine's cake",
    "christmas branch",
    "christmas wreath",
    "dead plaguesmith",
    "valentine's card",
    "bar of chocolate",
    "fireworks rocket",
    "barbarian banner",
    "ship rudder hole",
    "flask with paint",
    "slain braindeath",
    "dead frost giant",
    "blacksteel sword",
    "dragonbone staff",
    "spiked squelcher",
    "mammoth fur cape",
    "magicall inkwell",
    "empty flower pot",
    "fiery knight axe",
    "fiery heroic axe",
    "fiery war hammer",
    "icy mystic blade",
    "icy dragonslayer",
    "icy crystal mace",
    "dark mage statue",
    "earth knight axe",
    "earth heroic axe",
    "earth war hammer",
    "armillary sphere",
    "test-tube holder",
    "sanctified grave",
    "exploding cookie",
    "snowy birch tree",
    "dead sea serpent",
    "bricklayers' kit",
    "dark lord's cape",
    "springsprout rod",
    "wand of draconia",
    "slain bog raider",
    "Santiago's piano",
    "golden newspaper",
    "yummy gummy worm",
    "shield and sword",
    "corkscrew stairs",
    "dust of Lersatio",
    "brocade backpack",
    "dead mutated bat",
    "dead mutated rat",
    "broken apparatus",
    "firewalker boots",
    "crystal of focus",
    "crystal pedestal",
    "crystal of power",
    "veggie casserole",
    "epaminondas doll",
    "Worm queen Tooth",
    "bloodkiss flower",
    "limestone pillar",
    "shockwave amulet",
    "Helmet of Nature",
    "club of the fury",
    "farmer's avenger",
    "statue of Fafnar",
    "limestone window",
    "spookey blue eye",
    "frost giant pelt",
    "half-eaten brain",
    "mutated rat tail",
    "jade spike plant",
    "trollhair plants",
    "almanac of magic",
    "carniphila seeds",
    "sulphurous stone",
    "spiked iron ball",
    "petrified scream",
    "dead sandcrawler",
    "protective charm",
    "geomancer's robe",
    "necromantic robe",
    "pot of blackjack",
    "souleater trophy",
    "royal scale robe",
    "black jade cobra",
    "Cursed Gladiator",
    "Grimgor Guteater",
    "Haunted Treeling",
    "Apprentice Sheng",
    "Mad Technomancer",
    "Dragon Hatchling",
    "Energy Elemental",
    "Goblin Scavenger",
    "Yellow Butterfly",
    "Pirate Buccaneer",
    "Pirate Cutthroat",
    "Hellfire Fighter",
    "Skeleton Warrior",
    "Undead Gladiator",
    "Eye of the Seven",
    "green claw swamp",
    "captain bluebear",
    "lord paulistinha",
    "Guardian Halberd",
    "sandstone floor",
    "nothing special",
    "closed trapdoor",
    "marble flooring",
    "ornamented wall",
    "marble fountain",
    "minotaur statue",
    "watchdog statue",
    "gargoyle statue",
    "open fence gate",
    "oriental pillar",
    "luxurious couch",
    "standing mirror",
    "oriental carpet",
    "scarab ornament",
    "purple tapestry",
    "yellow tapestry",
    "orange tapestry",
    "behemoth trophy",
    "minotaur trophy",
    "yellow backpack",
    "purple backpack",
    "golden backpack",
    "lit candelabrum",
    "lit candlestick",
    "lit pumpkinhead",
    "ring of the sky",
    "bronze necklace",
    "silver necklace",
    "sapphire amulet",
    "magic lightwand",
    "platinum amulet",
    "wand of inferno",
    "garlic necklace",
    "dragon necklace",
    "ring of healing",
    "stalagmite rune",
    "magic wall rune",
    "fire field rune",
    "Santa's Mailbox",
    "helmet ornament",
    "tear of Daraman",
    "ornamented ankh",
    "magic longsword",
    "stonecutter axe",
    "enchanted staff",
    "daramanian mace",
    "hammer of wrath",
    "crusader helmet",
    "ceremonial mask",
    "guardian shield",
    "beholder shield",
    "snowy dead tree",
    "some sunflowers",
    "orange mushroom",
    "dead fire devil",
    "slain bonebeast",
    "bamboo palisade",
    "huntress statue",
    "bamboo wardrobe",
    "giant footprint",
    "ivory chair kit",
    "trunk chair kit",
    "small table kit",
    "round table kit",
    "stone table kit",
    "trunk table kit",
    "beastslayer axe",
    "horseman helmet",
    "charmer's tiara",
    "beholder helmet",
    "sentinel shield",
    "crocodile boots",
    "snake nest bush",
    "turtle sprouter",
    "purple cardinal",
    "giggle mushroom",
    "giant tree root",
    "dead carniphila",
    "lifeless nettle",
    "explorer brooch",
    "dwarven pickaxe",
    "ship cabin wall",
    "electric sparks",
    "striped marquee",
    "crossed weapons",
    "pirate tapestry",
    "tortoise's nest",
    "dry griffinclaw",
    "dead blood crab",
    "medal of honour",
    "golden figurine",
    "fighting spirit",
    "warrior's sweat",
    "chicken feather",
    "pirate backpack",
    "letter to Eremo",
    "weapon rack kit",
    "tortoise shield",
    "slain lost soul",
    "slain destroyer",
    "elemental ashes",
    "dead juggernaut",
    "demonic essence",
    "christmas token",
    "worn soft boots",
    "ceremonial ankh",
    "fur wall window",
    "snowy pine tree",
    "ice wall window",
    "inactive geyser",
    "piece of cactus",
    "mushroom spores",
    "slain ice golem",
    "frozen behemoth",
    "enchanted spear",
    "mammoth whopper",
    "demonrage sword",
    "mercenary sword",
    "diamond sceptre",
    "assassin dagger",
    "imaginary staff",
    "queen's sceptre",
    "nightmare blade",
    "dreaded cleaver",
    "blessed sceptre",
    "sapphire hammer",
    "bullseye potion",
    "krimhorn helmet",
    "whoopee cushion",
    "signed contract",
    "icy spike sword",
    "icy relic sword",
    "icy headchopper",
    "icy orcish maul",
    "obsidian statue",
    "lightning boots",
    "glimmering soil",
    "tunnel entrance",
    "antidote potion",
    "magician's robe",
    "sorcerer statue",
    "guardian statue",
    "jalapeño pepper",
    "swamplair armor",
    "oracle figurine",
    "thread of screw",
    "golden ornament",
    "dust of Marziel",
    "pitch black gap",
    "velvet tapestry",
    "strange machine",
    "dracoyle statue",
    "glob of mercury",
    "swamp tentacles",
    "red square book",
    "golem blueprint",
    "mechanical fish",
    "dead braindeath",
    "orange backpack",
    "egg of the Many",
    "elvish talisman",
    "poisonous slime",
    "wyvern talisman",
    "book of prayers",
    "mutated bat ear",
    "carrying device",
    "dragonbone tree",
    "thornpeak grass",
    "infected throne",
    "crocodile steak",
    "terrorbird beak",
    "winter wolf fur",
    "lizard backpack",
    "dead gnarlhound",
    "dragon tapestry",
    "widow mandibles",
    "high guard flag",
    "terramite shell",
    "beetle necklace",
    "broken crossbow",
    "hunter's quiver",
    "small pitchfork",
    "faded last will",
    "broken key ring",
    "botany almanach",
    "brimstone shell",
    "Orcus the Cruel",
    "Spirit of Earth",
    "Spirit of Water",
    "The Dark Dancer",
    "Gnorre Chyllson",
    "The Obliverator",
    "Son of Verminor",
    "Countess Sorrow",
    "Deadeye Devious",
    "Man In The Cave",
    "The Abomination",
    "Nightmare Scion",
    "Dwarf Geomancer",
    "Energy Overlord",
    "Earth Elemental",
    "Phantasm Summon",
    "Goblin Assassin",
    "Water Elemental",
    "Lizard Sentinel",
    "Minotaur Archer",
    "Pirate Marauder",
    "Quara Mantassin",
    "Betrayed Wraith",
    "Pirate Skeleton",
    "Dark Apprentice",
    "Shredderthrower",
    'utevo res ina "',
    "adevo grav flam",
    "adori gran flam",
    'exani hur "down',
    "adevo grav tera",
    "exevo grav vita",
    "jakundaf desert",
    "plains of havoc",
    "fields of glory",
    "minotaur archer",
    "lizard sentinel",
    "Quara Mantassin",
    "Dreaded Cleaver",
    "Demonrage Sword",
    "Assassin Dagger",
    "Executioner Axe",
    "Crusader Helmet",
    "Platinum Amulet",
    "sandstone tile",
    "sandstone wall",
    "stone flooring",
    "loose ice pile",
    "framework wall",
    "unlit campfire",
    "dwarven statue",
    "wooden railing",
    "broken obelisk",
    "pendulum clock",
    "treasure chest",
    "green tapestry",
    "white tapestry",
    "cyclops trophy",
    "the holy Tible",
    "green backpack",
    "small oil lamp",
    "lit table lamp",
    "simple fanfare",
    "christmas tree",
    "exotic flowers",
    "emerald bangle",
    "ancient amulet",
    "small sapphire",
    "small amethyst",
    "amulet of loss",
    "strange symbol",
    "wand of vortex",
    "boots of haste",
    "broken pottery",
    "avalanche rune",
    "chameleon rune",
    "fire wall rune",
    "fire bomb rune",
    "explosion rune",
    "hat of the mad",
    "damaged helmet",
    "stuffed rabbit",
    "ring of wishes",
    "carrot of doom",
    "throwing knife",
    "thunder hammer",
    "obsidian lance",
    "leather helmet",
    "warrior helmet",
    "strange helmet",
    "soldier helmet",
    "studded helmet",
    "dwarven helmet",
    "blessed shield",
    "dwarven shield",
    "studded shield",
    "ancient shield",
    "griffin shield",
    "vampire shield",
    "phoenix shield",
    "tempest shield",
    "stamped parcel",
    "stamped letter",
    "ranger's cloak",
    "bunch of wheat",
    "snowy fir tree",
    "heaven blossom",
    "small fir tree",
    "blueberry bush",
    "white mushroom",
    "brown mushroom",
    "some mushrooms",
    "green mushroom",
    "dark mushrooms",
    "slain skeleton",
    "snake ornament",
    "large cauldron",
    "brown bear fur",
    "polar bear fur",
    "sofa chair kit",
    "tusk chair kit",
    "coal basin kit",
    "tusk table kit",
    "table lamp kit",
    "camouflage bag",
    "green wig bush",
    "sneeze blossom",
    "dead crocodile",
    "dead centipede",
    "dead butterfly",
    "dead tarantula",
    "spectral stone",
    "steering wheel",
    "ball on chains",
    "small branches",
    "metal fittings",
    "wooden whistle",
    "training dummy",
    "stuffed dragon",
    "grappling hook",
    "juice squeezer",
    "poison trickle",
    "lizard leather",
    "ferumbras' hat",
    "obsidian knife",
    "beach backpack",
    "lottery ticket",
    "armor rack kit",
    "dead destroyer",
    "dead hellhound",
    "dead nightmare",
    "christmas card",
    "bat decoration",
    "gingerbreadman",
    "violet sulphur",
    "frozen railing",
    "frozen drawers",
    "baby seal doll",
    "memory crystal",
    "frostbite herb",
    "frozen mammoth",
    "ice cream cone",
    "justice seeker",
    "ornamented axe",
    "cranial basher",
    "berserk potion",
    "shadow sceptre",
    "mummy disguise",
    "large seashell",
    "File AH-X17L89",
    "barrel of beer",
    "elvenhair rope",
    "flower bouquet",
    "icy knight axe",
    "icy heroic axe",
    "icy war hammer",
    "strange statue",
    "huge telescope",
    "energy war axe",
    "glacier amulet",
    "lightning legs",
    "lightning robe",
    "yellow bed kit",
    "sparkling gems",
    "eternal flames",
    "neutral matter",
    "brown pavement",
    "Zirella's cart",
    "dead cockroach",
    "burried coffin",
    "energy barrier",
    "chocolate cake",
    "royal crossbow",
    "silkweaver bow",
    "greenwood coat",
    "hibiscus dress",
    "rainbow shield",
    "underworld rod",
    "wand of voodoo",
    "hellforged axe",
    "bulb of garlic",
    "pile of stones",
    "stone gargoyle",
    "stone pedestal",
    "dust of Arthei",
    "dust of Boreth",
    "research notes",
    "matrix crystal",
    "yalahari armor",
    "crystal column",
    "slain treeling",
    "broken machine",
    "dead hellspawn",
    "vampiric crest",
    "royal tapestry",
    "silky tapestry",
    "dead war golem",
    "bundle of rags",
    "champion's cup",
    "cocktail glass",
    "limestone wall",
    "glutton's mace",
    "musician's bow",
    "shield of care",
    "goddess statue",
    "serpent shield",
    "demon backpack",
    "crown backpack",
    "midnight shard",
    "scarab pincers",
    "polar bear paw",
    "ghostly tissue",
    "diabolic hedge",
    "pestilent fern",
    "necrotic grass",
    "universal tool",
    "glowing switch",
    "heart backpack",
    "nightmare doll",
    "hellspawn tail",
    "nettle blossom",
    "guardian boots",
    "expedition bag",
    "weaver wandtip",
    "corrupted flag",
    "broken halberd",
    "dead terramite",
    "terramite eggs",
    "terramite legs",
    "small notebook",
    "cultish symbol",
    "quara tentacle",
    "mantassin tail",
    "exquisite silk",
    "spectral cloth",
    "exquisite wood",
    "draken sulphur",
    "tentacle piece",
    "dead souleater",
    "lizard essence",
    "brimstone fang",
    "Crystal Spider",
    "Spirit of Fire",
    "Svoren the Mad",
    "Elder Beholder",
    "General Murius",
    "Ron the Ripper",
    "The Handmaiden",
    "The Horned Fox",
    "Earth Overlord",
    "Frost Giantess",
    "Ancient Scarab",
    "Blue Butterfly",
    "Pink Butterfly",
    "Lizard Templar",
    "Minotaur Guard",
    "Halloween Hare",
    "Pirate Corsair",
    "Fire Elemental",
    "Quara Predator",
    "Demon Skeleton",
    "Troll Champion",
    "Crypt Shambler",
    "exevo con mort",
    "adevo grav vis",
    "exevo mort hur",
    "exevo con flam",
    "exevo flam hur",
    "adevo mas flam",
    "utevo gran lux",
    "adevo grav pox",
    "adevo res flam",
    "utani gran hur",
    "adori vita vis",
    "exana mas mort",
    "demon skeleton",
    "minotaur guard",
    "amulet of loss",
    "amulet of life",
    "setzer gambler",
    "Quara Predator",
    "Krimhorn Sword",
    "Obsidian Lance",
    "Noxious Scythe",
    "Obsidian Lance",
    "Dwarven Helmet",
    "Ferumbras' Hat",
    "Hellforged Axe",
    "open trapdoor",
    "stone archway",
    "wall fountain",
    "wooden stairs",
    "buried coffin",
    "flag of Tibia",
    "goblin statue",
    "strange holes",
    "marble pillar",
    "stone railing",
    "rocking chair",
    "yellow pillow",
    "wooden coffin",
    "lemonade cask",
    "big wine cask",
    "blue tapestry",
    "dragon trophy",
    "blue backpack",
    "gray backpack",
    "broken bottle",
    "large amphora",
    "lit wall lamp",
    "royal fanfare",
    "potted flower",
    "rocking horse",
    "golden amulet",
    "ruby necklace",
    "silver brooch",
    "scarab amulet",
    "golden fruits",
    "ancient tiara",
    "small diamond",
    "small emerald",
    "platinum coin",
    "silver amulet",
    "bronze amulet",
    "orb of nature",
    "snakebite rod",
    "hailstorm rod",
    "moonlight rod",
    "wand of decay",
    "broken amulet",
    "piece of iron",
    "human remains",
    "stone rubbish",
    "antidote rune",
    "paralyze rune",
    "fireball rune",
    "soulfire rune",
    "family brooch",
    "crystal arrow",
    "burning heart",
    "portable hole",
    "throwing star",
    "silver dagger",
    "warlord sword",
    "serpent sword",
    "poison dagger",
    "battle hammer",
    "golden sickle",
    "clerical mace",
    "barbarian axe",
    "dragon hammer",
    "heavy machete",
    "ravager's axe",
    "pharaoh sword",
    "leather armor",
    "golden helmet",
    "viking helmet",
    "winged helmet",
    "legion helmet",
    "studded armor",
    "horned helmet",
    "amazon helmet",
    "dwarven armor",
    "wooden shield",
    "battle shield",
    "dragon shield",
    "copper shield",
    "viking shield",
    "castle shield",
    "medusa shield",
    "amazon shield",
    "scarab shield",
    "wooden hammer",
    "kitchen knife",
    "patched boots",
    "leather boots",
    "bunnyslippers",
    "mystic turban",
    "northern pike",
    "lump of dough",
    "old rush wood",
    "royal blossom",
    "wood mushroom",
    "dark mushroom",
    "fire mushroom",
    "dead minotaur",
    "dead scorpion",
    "dead beholder",
    "dead behemoth",
    "slain vampire",
    "slain banshee",
    "dead gargoyle",
    "dead skeleton",
    "grass archway",
    "painted stone",
    "sacred statue",
    "lizard statue",
    "bamboo column",
    "broken pillar",
    "bamboo drawer",
    "block of wood",
    "big table kit",
    "telescope kit",
    "hunting spear",
    "leopard armor",
    "bees ballroom",
    "titans orchid",
    "dead elephant",
    "dead flamingo",
    "shallow water",
    "old parchment",
    "sharp icicles",
    "burning skull",
    "monkey statue",
    "lava fountain",
    "wooden window",
    "wooden planks",
    "wooden column",
    "barred window",
    "dead tortoise",
    "water trickle",
    "pirate statue",
    "golden goblet",
    "silver goblet",
    "bronze goblet",
    "sniper gloves",
    "spool of yarn",
    "dwarven beard",
    "magic sulphur",
    "hardened bone",
    "goldfish bowl",
    "behemoth claw",
    "dead war wolf",
    "dead torturer",
    "birthday card",
    "marble window",
    "bamboo window",
    "infernal bolt",
    "Dracola's eye",
    "green sulphur",
    "party trumpet",
    "green balloon",
    "wooden pillar",
    "mammoth skull",
    "mammoth totem",
    "wooden dragon",
    "rainbow trout",
    "frozen trough",
    "frozen dragon",
    "flame of life",
    "piercing bolt",
    "assassin star",
    "golden trophy",
    "silver trophy",
    "bronze trophy",
    "crimson sword",
    "dragon slayer",
    "haunted blade",
    "butcher's axe",
    "crystal sword",
    "ragnir helmet",
    "special flask",
    "mining helmet",
    "heavy package",
    "energy shrine",
    "spider victim",
    "health potion",
    "dead squirrel",
    "fiery war axe",
    "dragon statue",
    "celestial map",
    "flaming arrow",
    "earth war axe",
    "glacier boots",
    "magma monocle",
    "green bed kit",
    "cave entrance",
    "marlin trophy",
    "jagged stones",
    "scarab cheese",
    "magical watch",
    "secret letter",
    "strange stone",
    "orcish banner",
    "large crystal",
    "cockroach leg",
    "battering ram",
    "covered wagon",
    "magic barrier",
    "valuable vase",
    "warsinger bow",
    "velvet mantle",
    "voltage armor",
    "paladin armor",
    "northwind rod",
    "demonwing axe",
    "emerald sword",
    "golden falcon",
    "norseman doll",
    "strange whirl",
    "blood crystal",
    "family banner",
    "small balcony",
    "ghost residue",
    "yalahari mask",
    "stone carving",
    "weird machine",
    "flower wreath",
    "coconut shoes",
    "magical torch",
    "crystal table",
    "blessed steak",
    "metal fitting",
    "worm punisher",
    "Carlin banner",
    "Carlin shield",
    "headache pill",
    "pigeon trophy",
    "moon backpack",
    "ancient stone",
    "bloody pincer",
    "gauze bandage",
    "scorpion tail",
    "vampire teeth",
    "tainted plant",
    "soul contract",
    "dragon banner",
    "serpent crest",
    "crystal boots",
    "tarantula egg",
    "dragon throne",
    "centipede leg",
    "lump of earth",
    "mutated flesh",
    "dead marauder",
    "zaoan halberd",
    "lizard trophy",
    "marble statue",
    "snake sceptre",
    "broken helmet",
    "dragon's tail",
    "jewelled belt",
    "minotaur horn",
    "shamanic hood",
    "magic crystal",
    "broken slicer",
    "downy feather",
    "Poison Spider",
    "The Hairy One",
    "Rotworm Queen",
    "The Old Widow",
    "Undead Minion",
    "Dark Torturer",
    "Dwarf Soldier",
    "Cyclops Drone",
    "Cyclops Smith",
    "Goblin Leader",
    "Red Butterfly",
    "Minotaur Mage",
    "Silver Rabbit",
    "Training Monk",
    "Mutated Human",
    "Mutated Tiger",
    "Orc Berserker",
    "Crazed Beggar",
    "Fire Overlord",
    "Quara Pincher",
    "Serpent Spawn",
    "Undead Dragon",
    "Dark Magician",
    "Mad Scientist",
    "Plaguethrower",
    "Poisonthrower",
    "Vampire Bride",
    "exevo vis lux",
    "adevo mas vis",
    "adevo res pox",
    "adevo mas hur",
    'exani hur "up',
    "adevo mas pox",
    "exevo con pox",
    "exevo con vis",
    "utevo vis lux",
    "mount sternum",
    "poison spider",
    "dwarf soldier",
    "orc berserker",
    "king tibianus",
    "Quara Pincher",
    "Dracoyle Mace",
    "Demonwing Axe",
    "Dragon Slayer",
    "Mourning Star",
    "Golden Helmet",
    "Legion Helmet",
    "Mystic Turban",
    "Orcish Helmet",
    "Paladin Armor",
    "Raptor Helmet",
    "Viking Helmet",
    "earth ground",
    "wooden floor",
    "brick window",
    "mystic flame",
    "stone coffin",
    "angel statue",
    "cobra statue",
    "poison field",
    "energy field",
    "searing fire",
    "stone pillar",
    "square table",
    "wooden chair",
    "heart pillow",
    "green pillow",
    "red tapestry",
    "cuckoo clock",
    "demon trophy",
    "flowery wall",
    "red backpack",
    "blue amphora",
    "water splash",
    "torch bearer",
    "wooden flute",
    "indoor plant",
    "honey flower",
    "wedding ring",
    "elven brooch",
    "crystal ring",
    "crystal coin",
    "stealth ring",
    "life crystal",
    "crystal wand",
    "necrotic rod",
    "crystal ball",
    "elven amulet",
    "dwarven ring",
    "broken sword",
    "moldy cheese",
    "burnt scroll",
    "fish remains",
    "wooden trash",
    "dragonfetish",
    "helmet piece",
    "ancient rune",
    "morning star",
    "carlin sword",
    "combat knife",
    "bright sword",
    "dragon lance",
    "crystal mace",
    "studded club",
    "arcane staff",
    "steel helmet",
    "chain helmet",
    "brass helmet",
    "devil helmet",
    "golden armor",
    "studded legs",
    "knight armor",
    "crown helmet",
    "demon helmet",
    "royal helmet",
    "amazon armor",
    "dwarven legs",
    "native armor",
    "steel shield",
    "plate shield",
    "brass shield",
    "crown shield",
    "demon shield",
    "great shield",
    "tower shield",
    "black shield",
    "poison arrow",
    "wooden spoon",
    "oven spatula",
    "white castle",
    "white knight",
    "white bishop",
    "black castle",
    "black knight",
    "black bishop",
    "golden boots",
    "leather legs",
    "simple dress",
    "magician hat",
    "yellow maple",
    "coconut palm",
    "white flower",
    "grave flower",
    "shadow plant",
    "dusk catcher",
    "jungle grass",
    "red mushroom",
    "dead cyclops",
    "dead rotworm",
    "dead pharaoh",
    "stone stairs",
    "small pagoda",
    "skull candle",
    "short pillar",
    "rope railing",
    "bamboo fence",
    "bamboo table",
    "bamboo shelf",
    "birdcage kit",
    "ripper lance",
    "banana staff",
    "bamboo plant",
    "jungle vines",
    "chill nettle",
    "jungle bells",
    "gold blossom",
    "velvet petal",
    "dead chicken",
    "dead merlkin",
    "memory stone",
    "hydra's nest",
    "ship railing",
    "rudder blade",
    "burning wall",
    "energy fence",
    "treasure map",
    "wooden plank",
    "rusty anchor",
    "pirate boots",
    "green carpet",
    "brown carpet",
    "dead mammoth",
    "voodoo skull",
    "tortoise egg",
    "spiral shell",
    "light shovel",
    "dead seagull",
    "skull helmet",
    "target board",
    "lizard scale",
    "beholder eye",
    "turtle shell",
    "vampire dust",
    "large throne",
    "wooden stake",
    "mermaid comb",
    "pirate shirt",
    "tree archway",
    "large branch",
    "tendril wall",
    "bookcase kit",
    "stone window",
    "dead defiler",
    "coloured egg",
    "ruthless axe",
    "surprise bag",
    "icy mountain",
    "skull pillar",
    "frozen chest",
    "frozen chair",
    "fine sulphur",
    "hydra tongue",
    "stone throne",
    "frozen demon",
    "frozen human",
    "dead chakoya",
    "dead penguin",
    "fur backpack",
    "sniper arrow",
    "mystic blade",
    "Thaian sword",
    "abyss hammer",
    "reaper's axe",
    "skullcrusher",
    "glorious axe",
    "norse shield",
    "earth shrine",
    "disguise kit",
    "watering can",
    "shiver arrow",
    "terra mantle",
    "terra amulet",
    "magma amulet",
    "glacier kilt",
    "glacier robe",
    "glacier mask",
    "blue bed kit",
    "potion stand",
    "trophy stand",
    "jester staff",
    "hallowed axe",
    "natural soil",
    "heap of sand",
    "hydra statue",
    "druid statue",
    "sturdy chest",
    "jagged sword",
    "water vortex",
    "fire barrier",
    "chain bolter",
    "serpent coat",
    "spirit cloak",
    "summer dress",
    "girl's dress",
    "divine plate",
    "molten plate",
    "frozen plate",
    "slain reaper",
    "vampire doll",
    "vampire lord",
    "copper pipes",
    "copper wheel",
    "brass throne",
    "blood goblet",
    "eaves gutter",
    "ghost's tear",
    "large window",
    "small window",
    "rusty shield",
    "rusty helmet",
    "slain zombie",
    "flower dress",
    "rust remover",
    "dead gozzler",
    "rotworm stew",
    "dark essence",
    "deep crystal",
    "slain medusa",
    "cobra tongue",
    "cultish mask",
    "cultish robe",
    "gear crystal",
    "frosty heart",
    "boggy dreads",
    "lump of dirt",
    "rare crystal",
    "baby rotworm",
    "tribal crest",
    "crab pincers",
    "stuffed toad",
    "werewolf fur",
    "mammoth tusk",
    "snowman doll",
    "zaoan helmet",
    "undead heart",
    "marked crate",
    "lump of clay",
    "sacred earth",
    "bamboo stick",
    "battle stone",
    "luminous orb",
    "dirty turban",
    "noble turban",
    "quara pincer",
    "strong sinew",
    "draken boots",
    "coconut milk",
    "Carrion Worm",
    "Giant Spider",
    "Deathbringer",
    "The Pit Lord",
    "Slime Summon",
    "Dire Penguin",
    "Mercury Blob",
    "Lethal Lissy",
    "The Evil Eye",
    "Diabolic Imp",
    "Nightstalker",
    "Frost Dragon",
    "Elf Arcanist",
    "Crimson Frog",
    "Worker Golem",
    "Pirate Ghost",
    "Ice Overlord",
    "Orc Spearman",
    "Black Knight",
    "Wild Warrior",
    "Flamethrower",
    "Magicthrower",
    "Island Troll",
    "Blightwalker",
    "ulderek rock",
    "dwarf bridge",
    "orc spearman",
    "giant spider",
    "elf arcanist",
    "leather legs",
    "golden armor",
    "royal helmet",
    "Giant Spider",
    "Knight Sword",
    "Viking Sword",
    "Mystic Blade",
    "Throwing Axe",
    "Demon Helmet",
    "Devil Helmet",
    "Elven Amulet",
    "Knight Armor",
    "Royal Helmet",
    "Steel Helmet",
    "Stout Shield",
    "muddy floor",
    "stalagmites",
    "stone floor",
    "tiled floor",
    "sewer grate",
    "wooden roof",
    "closed door",
    "small stone",
    "mossy stone",
    "water basin",
    "marble well",
    "small basin",
    "water wheel",
    "sarcophagus",
    "dragon flag",
    "castle flag",
    "street sign",
    "hero statue",
    "street lamp",
    "small table",
    "blue pillow",
    "large trunk",
    "wall mirror",
    "wolf trophy",
    "deer trophy",
    "lion trophy",
    "blank paper",
    "gemmed book",
    "purple tome",
    "blue bottle",
    "green flask",
    "beer bottle",
    "candelabrum",
    "candlestick",
    "magical key",
    "crystal key",
    "pumpkinhead",
    "god flowers",
    "flower bowl",
    "wooden doll",
    "star amulet",
    "holy scarab",
    "holy falcon",
    "white pearl",
    "black pearl",
    "gold nugget",
    "scarab coin",
    "energy ring",
    "banana skin",
    "rotten meat",
    "metal trash",
    "icicle rune",
    "voodoo doll",
    "phoenix egg",
    "gemmed lamp",
    "roc feather",
    "spike sword",
    "giant sword",
    "magic sword",
    "short sword",
    "broad sword",
    "iron hammer",
    "silver mace",
    "dwarven axe",
    "skull staff",
    "golden mace",
    "djinn blade",
    "iron helmet",
    "plate armor",
    "chain armor",
    "brass armor",
    "golden legs",
    "knight legs",
    "scale armor",
    "noble armor",
    "crown armor",
    "dark helmet",
    "demon armor",
    "ranger legs",
    "dark shield",
    "rose shield",
    "bone shield",
    "burst arrow",
    "baking tray",
    "rolling pin",
    "yellow vase",
    "closed trap",
    "fishing rod",
    "depot chest",
    "black token",
    "white token",
    "white queen",
    "black queen",
    "steel boots",
    "green tunic",
    "white dress",
    "brown bread",
    "moonflowers",
    "moon flower",
    "yellow rose",
    "love flower",
    "orange star",
    "holy orchid",
    "mire sprout",
    "swamp lilly",
    "sludge fern",
    "powder herb",
    "shadow herb",
    "troll green",
    "dead spider",
    "dead dragon",
    "slain ghoul",
    "slain demon",
    "dead goblin",
    "dead rabbit",
    "dead scarab",
    "dead hyaena",
    "dead efreet",
    "dead badger",
    "bamboo wall",
    "poison well",
    "bamboo lamp",
    "bamboo pole",
    "rope bridge",
    "wooden bars",
    "stone table",
    "thick trunk",
    "ivory chair",
    "small trunk",
    "fishing net",
    "dresser kit",
    "tribal mask",
    "tusk shield",
    "orange tree",
    "thread tree",
    "monkey tail",
    "fairy queen",
    "crane plant",
    "dawn singer",
    "jungle rose",
    "meadow star",
    "fallen tree",
    "dead kongra",
    "dead sibang",
    "dead parrot",
    "funeral urn",
    "pirate flag",
    "canopic jar",
    "some skulls",
    "panda teddy",
    "banana tree",
    "wooden wall",
    "pawpaw tree",
    "ocean floor",
    "sea anemone",
    "iron maiden",
    "wall chains",
    "rope-ladder",
    "blue carpet",
    "some shells",
    "stuck arrow",
    "weapon rack",
    "armour rack",
    "dragon claw",
    "poem scroll",
    "music sheet",
    "unholy book",
    "some cracks",
    "dead wyvern",
    "stony floor",
    "bone pillar",
    "tree window",
    "present bag",
    "certificate",
    "red balloon",
    "frozen wall",
    "mammoth fur",
    "wooden bull",
    "wooden yeti",
    "snowy stone",
    "buffer stop",
    "green perch",
    "stone shelf",
    "fragile ice",
    "raft rudder",
    "ship rudder",
    "frost charm",
    "frozen claw",
    "royal spear",
    "headchopper",
    "relic sword",
    "orcish maul",
    "havoc blade",
    "wyvern fang",
    "bloody edge",
    "runed sword",
    "jade hammer",
    "lunar staff",
    "taurus mace",
    "amber staff",
    "bonebreaker",
    "angelic axe",
    "ice mammoth",
    "executioner",
    "mythril axe",
    "fire shrine",
    "mana potion",
    "signet ring",
    "beach chair",
    "icy war axe",
    "astro clock",
    "flash arrow",
    "earth arrow",
    "terra boots",
    "magma boots",
    "red bed kit",
    "chalk board",
    "rifty earth",
    "energy soil",
    "mother soil",
    "pure energy",
    "dried grass",
    "wooden cart",
    "orcish pole",
    "armor parts",
    "chimney kit",
    "dragon robe",
    "belted cape",
    "lavos armor",
    "the stomper",
    "iron pillar",
    "Julius' map",
    "copper pipe",
    "small tower",
    "blood basin",
    "blood skull",
    "rain barrel",
    "jester doll",
    "animal cure",
    "ghost charm",
    "brocade bag",
    "rusty armor",
    "rusty boots",
    "glob of tar",
    "black skull",
    "small topaz",
    "carrot cake",
    "batwing hat",
    "love potion",
    "meat shield",
    "stone ledge",
    "fiery heart",
    "witch broom",
    "war crystal",
    "cyclops toe",
    "swamp grass",
    "pestbringer",
    "red lantern",
    "striped fur",
    "metal spike",
    "dark rosary",
    "shiny stone",
    "winged tail",
    "unholy bone",
    "warwolf fur",
    "santa teddy",
    "zaoan armor",
    "zaoan shoes",
    "zaoan sword",
    "shaggy tail",
    "zaogun flag",
    "sacred bowl",
    "sacred coal",
    "cauliflower",
    "ghoul snack",
    "purple robe",
    "nettle spit",
    "orcish gear",
    "orc leather",
    "pelvis bone",
    "banana sash",
    "mystic root",
    "twiceslicer",
    "cobra crown",
    "dragonfruit",
    "fruit juice",
    "Spit Nettle",
    "Terror Bird",
    "Minishabaal",
    "Necropharus",
    "The Imperor",
    "Winter wolf",
    "Plaguesmith",
    "Green Djinn",
    "Dragon Lord",
    "Dwarf Guard",
    "Orchid Frog",
    "Stone Golem",
    "Frost Giant",
    "Mutated Bat",
    "Mutated Rat",
    "Necromancer",
    "Orc Warlord",
    "Orc Warrior",
    "Gang Member",
    "Vashresamun",
    "Sea Serpent",
    "Black Sheep",
    "Infernalist",
    "Deathslicer",
    "Frost Troll",
    "Swamp Troll",
    "Grim Reaper",
    'exura sio "',
    "femor hills",
    "shadowthorn",
    "dragon lord",
    "green djinn",
    "carniphilla",
    "mana shield",
    "golden legs",
    "test server",
    "Dwarf Guard",
    "Quara Scout",
    "Short Sword",
    "Broad Sword",
    "Great Sword",
    "Magic Sword",
    "Dwarven Axe",
    "Headchopper",
    "Iron Hammer",
    "Wedding Axe",
    "The Avenger",
    "Ab'Dendriel",
    "Liberty Bay",
    "dirt floor",
    "stone wall",
    "small hole",
    "stone tile",
    "stone pile",
    "tiled roof",
    "brick wall",
    "metal wall",
    "drawbridge",
    "gravestone",
    "coal basin",
    "fire field",
    "magic wall",
    "poison gas",
    "sofa chair",
    "red pillow",
    "water cask",
    "red carpet",
    "blackboard",
    "orc trophy",
    "bloodstain",
    "mossy wall",
    "green tome",
    "yellow bag",
    "purple bag",
    "golden bag",
    "golden mug",
    "table lamp",
    "wooden key",
    "silver key",
    "copper key",
    "golden key",
    "water pipe",
    "teddy bear",
    "model ship",
    "piggy bank",
    "small ruby",
    "violet gem",
    "yellow gem",
    "might ring",
    "power ring",
    "mind stone",
    "sword ring",
    "paw amulet",
    "dirty cape",
    "blank rune",
    "spell rune",
    "dead human",
    "gem holder",
    "right horn",
    "spy report",
    "sword hilt",
    "cornucopia",
    "battle axe",
    "double axe",
    "war hammer",
    "fire sword",
    "ice rapier",
    "orcish axe",
    "knight axe",
    "bone sword",
    "heavy mace",
    "brass legs",
    "crown legs",
    "dark armor",
    "demon legs",
    "power bolt",
    "pitch fork",
    "white vase",
    "green vase",
    "white pawn",
    "white king",
    "black pawn",
    "black king",
    "plate legs",
    "chain legs",
    "dragon ham",
    "strawberry",
    "candy cane",
    "magic tree",
    "dwarf tree",
    "water lily",
    "goat grass",
    "swamp reed",
    "blood herb",
    "stone herb",
    "sling herb",
    "dead troll",
    "dead snake",
    "dead sheep",
    "dead dwarf",
    "dead djinn",
    "dead cobra",
    "dead larva",
    "slain lich",
    "dead marid",
    "dead skunk",
    "dead gazer",
    "earth hole",
    "grass wall",
    "small boat",
    "small sail",
    "snake wall",
    "dried well",
    "totem pole",
    "tusk table",
    "tusk chair",
    "badger fur",
    "drawer kit",
    "locker kit",
    "barrel kit",
    "trough kit",
    "didgeridoo",
    "lich staff",
    "bast skirt",
    "thorn bush",
    "tower fern",
    "small fern",
    "giant tree",
    "jungle maw",
    "dead hydra",
    "dead panda",
    "dead tiger",
    "dead dworc",
    "small cask",
    "white flag",
    "stony pond",
    "mango tree",
    "sugar cane",
    "demon dust",
    "small fish",
    "slimy wall",
    "antic well",
    "earth pile",
    "soul stone",
    "pirate bag",
    "demon horn",
    "pirate hat",
    "jewel case",
    "armor rack",
    "soft boots",
    "grass roof",
    "party cake",
    "death ring",
    "cream cake",
    "santa doll",
    "fur pillar",
    "stone base",
    "bone totem",
    "figurehead",
    "dead husky",
    "onyx arrow",
    "viper star",
    "heroic axe",
    "onyx flail",
    "chaos mace",
    "furry club",
    "elvish bow",
    "ice statue",
    "cat basket",
    "ice shrine",
    "spider egg",
    "spider web",
    "elven vase",
    "flower pot",
    "terra legs",
    "magma legs",
    "magma coat",
    "terra hood",
    "large hole",
    "jester hat",
    "dragonhead",
    "empty pipe",
    "tool parts",
    "invitation",
    "tree stump",
    "Ironworker",
    "spiderwebs",
    "focus cape",
    "ethno coat",
    "Mexcalibur",
    "toy spider",
    "iron floor",
    "small roof",
    "fire basin",
    "small gems",
    "large well",
    "old carpet",
    "gear wheel",
    "burnt wall",
    "rusty legs",
    "gold ignot",
    "black book",
    "golem part",
    "golem head",
    "sun emblem",
    "orange bag",
    "black hood",
    "wyrm scale",
    "snake skin",
    "high grass",
    "skunk tail",
    "stone wing",
    "hydra head",
    "mummy doll",
    "sabretooth",
    "scythe leg",
    "heavy ball",
    "zaoan legs",
    "twin hooks",
    "zaoan robe",
    "black wool",
    "skull belt",
    "quara bone",
    "safety pin",
    "goblin ear",
    "Polar Bear",
    "Braindeath",
    "Bog Raider",
    "Carniphila",
    "Death Blob",
    "Mr. Punish",
    "Blood Crab",
    "Fire Devil",
    "Juggernaut",
    "Blue Djinn",
    "Azure Frog",
    "Coral Frog",
    "Green Frog",
    "Orc Leader",
    "Orc Shaman",
    "Bone Beast",
    "adana mort",
    "adito tera",
    "adito grav",
    "adori flam",
    "exori flam",
    "exori mort",
    "adori gran",
    "exura gran",
    "adura gran",
    "exura gran",
    "adura gran",
    "exani tera",
    "utamo vita",
    "exura vita",
    "adura vita",
    "aleta grav",
    "mintwallin",
    "lighthouse",
    "orc shaman",
    "blue djinn",
    "Juggernaut",
    "Strawberry",
    "Long Sword",
    "Mage Sword",
    "Wyrm Sword",
    "Double Axe",
    "Battle Axe",
    "Soft Boots",
    "Gray Beach",
    "Mintwallin",
    "dirt wall",
    "lava hole",
    "time tile",
    "snow heap",
    "sandstone",
    "flat roof",
    "lava wall",
    "open door",
    "draw well",
    "millstone",
    "rush wood",
    "big table",
    "beer cask",
    "wine cask",
    "bloodspot",
    "parchment",
    "blue tome",
    "grey tome",
    "green bag",
    "waterskin",
    "wall lamp",
    "used lamp",
    "lit torch",
    "post horn",
    "bird cage",
    "gold coin",
    "green gem",
    "life ring",
    "time ring",
    "spellbook",
    "gold ring",
    "terra rod",
    "club ring",
    "dirty fur",
    "some wood",
    "torn book",
    "letterbag",
    "left horn",
    "blue note",
    "blood orb",
    "longsword",
    "great axe",
    "bone club",
    "small axe",
    "blue vase",
    "open trap",
    "telescope",
    "red tunic",
    "blue robe",
    "ball gown",
    "red apple",
    "blueberry",
    "plum tree",
    "red maple",
    "pear tree",
    "dead tree",
    "blue rose",
    "sunflower",
    "moon herb",
    "frog leaf",
    "star herb",
    "dead wolf",
    "dead deer",
    "dead bear",
    "dead lion",
    "dead wasp",
    "dead yeti",
    "ant trail",
    "mud stain",
    "waterfall",
    "grass mat",
    "straw mat",
    "dried fur",
    "tiger fur",
    "globe kit",
    "piano kit",
    "trunk kit",
    "dead crab",
    "rock soil",
    "hydra egg",
    "ship rail",
    "cat's paw",
    "rum flask",
    "shark fin",
    "dead toad",
    "stuck axe",
    "nose ring",
    "honeycomb",
    "slingshot",
    "dead frog",
    "beach bag",
    "fish tail",
    "dead bird",
    "eye patch",
    "tree wall",
    "tree hole",
    "santa hat",
    "party hat",
    "ice floor",
    "dark rock",
    "ore wagon",
    "mead horn",
    "baby seal",
    "empty jug",
    "berserker",
    "titan axe",
    "demonbone",
    "ravenwing",
    "royal axe",
    "noble axe",
    "fur boots",
    "toy mouse",
    "buoy line",
    "fine vase",
    "waterball",
    "blue legs",
    "spellwand",
    "Firlefanz",
    "demon oak",
    "iced soil",
    "dry grass",
    "bone claw",
    "steel axe",
    "lock pick",
    "raspberry",
    "Yol's bow",
    "solar axe",
    "dead wyrm",
    "iron wall",
    "mechanism",
    "large gem",
    "leaf legs",
    "witch hat",
    "lion mane",
    "wild vine",
    "orc tooth",
    "bony tail",
    "giant eye",
    "silky fur",
    "thick fur",
    "rice ball",
    "drakinata",
    "clay lump",
    "pineapple",
    "aubergine",
    "miraculum",
    "quara eye",
    "rope belt",
    "trollroot",
    "sedge hat",
    "manafluid",
    "lifefluid",
    "Tarantula",
    "Avalanche",
    "Acid Blob",
    "Annihilon",
    "Dharalion",
    "Ferumbras",
    "Ghazbaran",
    "Golgordan",
    "Hellgorak",
    "Morgaroth",
    "Orshabaal",
    "The Count",
    "Tibia Bug",
    "Hellhound",
    "Ice Golem",
    "Destroyer",
    "Hellspawn",
    "Nightmare",
    "Elf Scout",
    "War Golem",
    "Centipede",
    "Cockroach",
    "Dark Monk",
    "Priestess",
    "Orc Rider",
    "Gladiator",
    "Primitive",
    "Ashmunrah",
    "Morguthis",
    "Crocodile",
    "Bonebeast",
    "Lost Soul",
    "Ice Witch",
    "exana pox",
    "exana ina",
    "exeta res",
    "adevo ina",
    "exevo con",
    "adeta sio",
    "exeta vis",
    "exori vis",
    "exevo pan",
    "utani hur",
    "utana vid",
    "utevo lux",
    "adana ani",
    "aleta sio",
    "ankrahmun",
    "port hope",
    "kazordoon",
    "northport",
    "orshabaal",
    "ferumbras",
    "elf scout",
    "ashmunrah",
    "butterfly",
    "crocodile",
    "excalibug",
    "mordorion",
    "protected",
    "Elemental",
    "Honeycomb",
    "Twin Edge",
    "Frostbite",
    "Skull Axe",
    "Great Axe",
    "Berserker",
    "Might Axe",
    "Ankrahmun",
    "Kazordoon",
    "Port Hope",
    "Rathleton",
    "Rookgaard",
    "Svargrond",
    "trapdoor",
    "pedestal",
    "mountain",
    "paravent",
    "buttress",
    "fountain",
    "campfire",
    "monument",
    "wardrobe",
    "bookcase",
    "painting",
    "tapestry",
    "document",
    "red tome",
    "backpack",
    "blue bag",
    "gray bag",
    "lit lamp",
    "panpipes",
    "war horn",
    "bone key",
    "football",
    "snowball",
    "blue gem",
    "axe ring",
    "old twig",
    "fishbone",
    "big bone",
    "cookbook",
    "hand axe",
    "scimitar",
    "naginata",
    "fire axe",
    "twin axe",
    "crossbow",
    "red robe",
    "fir tree",
    "sycamore",
    "old tree",
    "red rose",
    "rosebush",
    "mud whip",
    "dry bush",
    "dead rat",
    "dead orc",
    "dead dog",
    "dead bug",
    "dead pig",
    "dead elf",
    "stairway",
    "ant-hill",
    "palisade",
    "harp kit",
    "big fern",
    "dead bat",
    "ice pick",
    "mandrake",
    "mangrove",
    "starfish",
    "fire bug",
    "shackles",
    "rum cask",
    "catapult",
    "ballista",
    "arbalest",
    "iron ore",
    "bat wing",
    "fish fin",
    "bear paw",
    "wolf paw",
    "soul orb",
    "tendrils",
    "oven kit",
    "skeleton",
    "ice wall",
    "fur wall",
    "entrance",
    "ice hole",
    "vile axe",
    "ice cube",
    "earmuffs",
    "contract",
    "seashell",
    "dead cat",
    "bug tral",
    "lavahole",
    "orc tusk",
    "crucible",
    "balloons",
    "drawbars",
    "mage hat",
    "cucumber",
    "beetroot",
    "Devileye",
    "calamity",
    "textbook",
    "CM token",
    "pavement",
    "pig foot",
    "drachaku",
    "jade hat",
    "broccoli",
    "old iron",
    "old cape",
    "lemonade",
    "Valkyrie",
    "Scorpion",
    "Bloodpaw",
    "Frostfur",
    "Drasilla",
    "Beholder",
    "Flamingo",
    "Demodras",
    "Fernfang",
    "Latrivan",
    "Madareth",
    "Massacre",
    "Ushuriel",
    "Zugurosh",
    "War wolf",
    "Werewolf",
    "Elephant",
    "Gargoyle",
    "Phantasm",
    "Behemoth",
    "Minotaur",
    "Squirrel",
    "Assassin",
    "Smuggler",
    "Dipthrah",
    "Cave Rat",
    "Skeleton",
    "Tortoise",
    "darashia",
    "draconia",
    "beholder",
    "valkyrie",
    "skeleton",
    "minotaur",
    "war wolf",
    "dipthrah",
    "elephant",
    "cipfried",
    "harmonia",
    "Behemoth",
    "Gargoyle",
    "Minotaur",
    "Skeleton",
    "Mushroom",
    "Zucchini",
    "Scimitar",
    "Hand Axe",
    "Tomahawk",
    "Vile Axe",
    "Mage Hat",
    "Darashia",
    "flowers",
    "pitfall",
    "archway",
    "obelisk",
    "counter",
    "drawers",
    "dresser",
    "dustbin",
    "picture",
    "cobwebs",
    "present",
    "red bag",
    "amphora",
    "fanfare",
    "red gem",
    "rubbish",
    "halberd",
    "hatchet",
    "crowbar",
    "machete",
    "war axe",
    "doublet",
    "cleaver",
    "mailbox",
    "inkwell",
    "sandals",
    "coconut",
    "pumpkin",
    "corncob",
    "anthill",
    "lantern",
    "hammock",
    "sundial",
    "bollard",
    "marquee",
    "bubbles",
    "pillory",
    "mermaid",
    "ape fur",
    "bandana",
    "peg leg",
    "firefly",
    "avenger",
    "ice hut",
    "icicles",
    "snowman",
    "mammoth",
    "fur bag",
    "impaler",
    "fur cap",
    "parasol",
    "crystal",
    "chimney",
    "drawbar",
    "odd hat",
    "antlers",
    "compass",
    "Rotworm",
    "Merlkin",
    "Bovinus",
    "The Hag",
    "Webster",
    "Defiler",
    "Chicken",
    "Penguin",
    "Seagull",
    "Dracola",
    "Grorlam",
    "Munster",
    "Gozzler",
    "Ungreez",
    "Mammoth",
    "Spectre",
    "Cyclops",
    "Stalker",
    "Mahrdis",
    "Rahemos",
    "Warlock",
    "Banshee",
    "Vampire",
    'exiva "',
    "rotworm",
    "warlock",
    "vampire",
    "seymour",
    "e-plate",
    "hunting",
    "botting",
    "fag key",
    "xiblitz",
    "eternia",
    "viplist",
    "Vampire",
    "Coconut",
    "Pumpkin",
    "Halberd",
    "Farmine",
    "Yalahar",
    "stairs",
    "ladder",
    "debris",
    "statue",
    "blades",
    "spikes",
    "throne",
    "locker",
    "mirror",
    "barrel",
    "trough",
    "banner",
    "emblem",
    "scroll",
    "basket",
    "bucket",
    "leaves",
    "dagger",
    "rapier",
    "sickle",
    "katana",
    "scythe",
    "shovel",
    "hammer",
    "parcel",
    "letter",
    "jacket",
    "salmon",
    "shrimp",
    "orange",
    "banana",
    "cherry",
    "grapes",
    "carrot",
    "tomato",
    "cookie",
    "cheese",
    "willow",
    "poplar",
    "cactus",
    "branch",
    "paddle",
    "stones",
    "pagoda",
    "bridge",
    "pillar",
    "gravel",
    "icicle",
    "anchor",
    "hawser",
    "pulley",
    "rubble",
    "turtle",
    "abacus",
    "twines",
    "planks",
    "geyser",
    "shield",
    "walnut",
    "peanut",
    "marlin",
    "bellow",
    "muzzle",
    "window",
    "potato",
    "candle",
    "mosaik",
    "helmet",
    "Amazon",
    "Kongra",
    "Sibang",
    "Spider",
    "Parrot",
    "Fluffy",
    "Efreet",
    "Dragon",
    "Goblin",
    "Scarab",
    "Badger",
    "Hacker",
    "Hyaena",
    "Rabbit",
    "Bandit",
    "Hunter",
    "Thalas",
    "Wyvern",
    "Medusa",
    "Zombie",
    "fibula",
    "venore",
    "drefia",
    "carlin",
    "demona",
    "rabbit",
    "dragon",
    "goblin",
    "amazon",
    "spider",
    "dragon",
    "scarab",
    "al dee",
    "hunted",
    "xaxaxa",
    "jajaja",
    "botter",
    "carpet",
    "shovel",
    "bubble",
    "antica",
    "secura",
    "elysia",
    "fejken",
    "Dragon",
    "Goblin",
    "Hyaena",
    "Medusa",
    "Wyvern",
    "Almond",
    "Banana",
    "Carrot",
    "Cheese",
    "Cherry",
    "Grapes",
    "Potato",
    "Tomato",
    "Katana",
    "Rapier",
    "Rapier",
    "Carlin",
    "Venore",
    "earth",
    "grass",
    "water",
    "stone",
    "grave",
    "smoke",
    "ashes",
    "slits",
    "fence",
    "table",
    "bench",
    "couch",
    "crate",
    "chest",
    "lever",
    "paper",
    "plate",
    "watch",
    "torch",
    "piano",
    "globe",
    "crown",
    "talon",
    "skull",
    "twigs",
    "broom",
    "sword",
    "sabre",
    "spear",
    "staff",
    "knife",
    "arrow",
    "anvil",
    "spoon",
    "label",
    "altar",
    "scarf",
    "melon",
    "bread",
    "flour",
    "beech",
    "wheat",
    "tulip",
    "agave",
    "liane",
    "crane",
    "liana",
    "vines",
    "rocks",
    "swamp",
    "mango",
    "coral",
    "straw",
    "shell",
    "lance",
    "atlas",
    "bones",
    "candy",
    "strut",
    "tusks",
    "rails",
    "husky",
    "shard",
    "cigar",
    "niche",
    "linen",
    "seeds",
    "birch",
    "grate",
    "wheel",
    "mould",
    "wagon",
    "lemon",
    "onion",
    "tunic",
    "gland",
    "screw",
    "steam",
    "slime",
    "jutty",
    "armor",
    "stand",
    "thorn",
    "acorn",
    "blood",
    "urine",
    "Achad",
    "Rocky",
    "Panda",
    "Gazer",
    "Slime",
    "Bones",
    "Xenia",
    "Husky",
    "Demon",
    "Marid",
    "Hydra",
    "Dwarf",
    "Tiger",
    "Ghost",
    "Larva",
    "Skunk",
    "Nomad",
    "Omruc",
    "Cobra",
    "Snake",
    "Sheep",
    "Mimic",
    "Witch",
    "Troll",
    "Ghoul",
    "Mummy",
    "exori",
    "exura",
    "adori",
    "edron",
    "thais",
    "senja",
    "folda",
    "snake",
    "demon",
    "troll",
    "mummy",
    "larva",
    "omruc",
    "hydra",
    "norma",
    "aruda",
    "runes",
    "trade",
    "lmfao",
    "leave",
    "level",
    "clear",
    "quest",
    "sword",
    "drags",
    "Demon",
    "Hydra",
    "Troll",
    "Witch",
    "Gorgo",
    "Tiger",
    "Apple",
    "Bread",
    "Melon",
    "Peach",
    "Sword",
    "Sabre",
    "Edron",
    "Thais",
    "Zzrat",
    "void",
    "dirt",
    "sand",
    "hole",
    "ramp",
    "lava",
    "snow",
    "mast",
    "sail",
    "sign",
    "bars",
    "oven",
    "book",
    "vial",
    "vase",
    "pool",
    "bowl",
    "lamp",
    "lyre",
    "lute",
    "drum",
    "harp",
    "doll",
    "rope",
    "ankh",
    "bone",
    "bill",
    "club",
    "mace",
    "epee",
    "bolt",
    "rake",
    "pick",
    "fork",
    "coat",
    "cape",
    "meat",
    "fish",
    "pear",
    "roll",
    "pine",
    "palm",
    "bush",
    "fern",
    "rock",
    "bear",
    "tusk",
    "worm",
    "ship",
    "kelp",
    "cart",
    "dice",
    "wood",
    "comb",
    "hook",
    "tree",
    "cake",
    "raft",
    "sled",
    "buoy",
    "tent",
    "bait",
    "nail",
    "note",
    "coal",
    "plum",
    "roof",
    "moss",
    "gate",
    "ring",
    "acid",
    "rice",
    "wool",
    "sais",
    "peas",
    "beer",
    "milk",
    "wine",
    "Slim",
    "Bear",
    "Thul",
    "Wolf",
    "Crab",
    "Fury",
    "Wyrm",
    "Lion",
    "Toad",
    "Wisp",
    "Yeti",
    "Wasp",
    "Deer",
    "Monk",
    "Hero",
    "Lich",
    "vega",
    "wolf",
    "hero",
    "mols",
    "swe?",
    "sell",
    "omfg",
    "rofl",
    "lmao",
    "haha",
    "haha",
    "boat",
    "help",
    "rope",
    "vial",
    "mace",
    "nova",
    "main",
    "cycs",
    "Hero",
    "Lich",
    "Wolf",
    "Fish",
    "Leaf",
    "Pear",
    "Plum",
    "ice",
    "tar",
    "box",
    "bed",
    "cot",
    "map",
    "bag",
    "mug",
    "cup",
    "jug",
    "orb",
    "axe",
    "bow",
    "hoe",
    "saw",
    "pot",
    "pan",
    "ham",
    "egg",
    "fur",
    "gem",
    "bat",
    "oil",
    "mud",
    "rum",
    "Dog",
    "Elf",
    "Cat",
    "Bug",
    "Bat",
    "Pig",
    "Orc",
    "Rat",
    "rat",
    "bug",
    "elf",
    "orc",
    "obi",
    "gfb",
    "hmm",
    "lmm",
    "poh",
    "poi",
    "mpa",
    "mls",
    "pl?",
    "br?",
    "aol",
    "buy",
    "job",
    "lol",
    "omg",
    "-.-",
    "exp",
    "469",
    "dls",
    "wls",
    "mpa",
    "sov",
    "sca",
    "Elf",
    "Orc",
    "Rat",
    "Axe",
    "Zao",
    "sd",
    "uh",
    "pz",
    "pk",
    "pg",
    "w8",
    "hi",
    "fs",
    "gs",
    "rh",
  ];
}
